stages:
- test
- name: deploy
  if: tag IS present
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pep8
before_script:
  - pep8 .
script:
  - python setup.py -q install
jobs:
  include:
  - stage: deploy
    python: '3.6'
    install: skip
    before_script: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      on:
        tags: true
      distributions: sdist bdist_wheel
      user: reportportal
      password:
        secure: <PyPI password encrypted using "gem install travis && travis encrypt --add deploy.password">
